### PR TITLE
Add barebones .travis.yml

### PR DESCRIPTION
**Pull request by aidantwoods**
Since you use Swift package manager, running the unit tests in CI is pretty easy. If this is desired, you'll of course need to configure Travis to actually test this repo too :)

### CODE REVIEW

**Comment by aidantwoods** [comment]
If you want to see an example Travis build, this file is basically just ripped from one of my projects – so a build will look a little like: https://travis-ci.org/aidantwoods/swift-paseto/builds/369824524.

You could also shave a considerable amount of time off the build depending on how pedantic you are about Homebrew being up to date before installing `libsodium`.

**Comment by aidantwoods** [comment]
@jedisct1 any chance at getting Travis set up? :) While I run the tests locally on the latest installation of Swift, this is probably the easiest way of verifying source compatibility with Swift 4.0 (I don't have it to test on)

**Comment by blochberger** [comment]
Can we enable testing for iOS in Travis as well?

**Comment by blochberger** [comment]
I missed that, thanks!

**Pull request merged**
