### PR TITLE
Use sodium_malloc(crypto_generichash_statebytes()) to alloc hash state struct

### PR DESCRIPTION
**Pull request by Westacular**
Addresses https://github.com/jedisct1/swift-sodium/issues/177

As of Xcode 10.2 beta 1 (i.e. the Swift 5 compiler, even in Swift 4 mode), Swift no longer bridges C types which have alignment sizes > 16 bytes, so instead of trying to alloc the `crypto_generichash_state` struct in Swift, malloc it using the recommended C functions and treat it as an `UnsafeMutableRawPointer`.

Wrapping it as a `OpaquePointer` is necessary for interacting with the other C APIs, but we need to also keep the original `UnsafeMutableRawPointer` in order to free the memory in deinit.

### CODE REVIEW

**Comment by jedisct1** [comment]
What happens exactly with types having a > 16 bytes alignment? If they end up being 16 bytes aligned, this is fine.

**Comment by Westacular** [comment]
Any struct where the C attributes specify an alignment requirement > 16 bytes gets treated as something that can't be represented in Swift — the struct itself is not imported, and all parameters that use it as a type instead show up as type `OpaquePointer?` in Swift. Exactly 16 is fine, however.

I've updated my PR such that it's compatible with both Xcode 10.0/1 and 10.2 (yay `#if compiler(>=5)`), but if crypto_generichash_blake2b.h can instead be modified to specify
```c
typedef struct CRYPTO_ALIGN(16) crypto_generichash_blake2b_state
```
that would be a nicer fix. (I didn't know enough about the underlying C implementation to guess at why it specified alignment of 64, or if it would be safe to change.)

**Comment by marwan87** [comment]
Is this fix going to be merged into the master branch

**Comment by rcamparoML** [comment]
Why this PR wasn't merged ? :(

**Comment by jedisct1** [comment]
This is redundant with 7de099998e5184c941c3723957157217b41829bd, and alignment is not required any more.

**Comment by jedisct1** [comment]
Backporting the code to obsolete Xcode versions should be pretty simple. Not sure if the precompiled binaries will be compatible, though. Probably, but this is completely untested and unsupported, so you're a bit on your own here.

**Pull request closed without merging**
