### PR TITLE
Expose features needed to implement the Scuttlebutt Protocol

### PR DESCRIPTION
**Pull request by marching-cube**
In order to implement the Scuttlebutt Protocol, a few more functions need to be exposed from the C Sodium library. Specifically:
- `crypto_scalarmult` is needed for the EC Diffie-Hellman computation,
- `crypto_sign_ed25519_pk_to_curve25519`/ `crypto_sign_ed25519_sk_to_curve25519` are needed so we can use the same keypair for signing and encryption,
- `crypto_hash_sha256` is used instead of the generic BLAKE2b.

Sodium's documentation puts them all in the Advanced section, that's why I am implementing a single Advanced class. Long term, it may be better to split it into separate categories?

Additionally, the current implementation of the SecretBox does not allow user to specify the nonce parameter manually, rather defaults to a random value. However, the protocol requires a fixed nonce value (all zeroes), so I have extended the SecretBox class with an additional `seal` method overload.

Reference:
https://ssbc.github.io/scuttlebutt-protocol-guide/

### CODE REVIEW

**Comment by jedisct1** [comment]
Adding these would be very sad.

swift-sodium tries to retain some sanity by exposing only high-level APIs in order to prevent misuse.

Adding the ability to specify a nonce, use scalarmult without proper hashing, expose a hashing function vulnerable to length extension, completely defeats this.

**Comment by indutny** [comment]
Would exposing `crypto_sign_ed25519_pk_to_curve25519` and `crypto_sign_ed25519_sk_to_curve25519` make the library less high-level? There is certainly a use case for this in my application as well as in secure scuttlebutt.

**Comment by jedisct1** [comment]
@indutny  Conversions between `sodium.sign.KeyPair`, `sodium.box.KeyPair` and `sodium.secretbox.KeyPair` can be added.

None of these should assume specific curves, so they can all fail.

**Comment by indutny** [comment]
I see. Thank you for taking time to explain!

**Pull request closed without merging**
